language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
 -postgresql    

env:
  global:
    - CODECLIMATE_REPO_TOKEN=9e83697183b61817c399b2199742dc61ed9f1c454e1d973774eafdc80807db67

    before_script:
  - cat .env >> .env
  - psql -c "DROP DATABASE travis;" -U postgres
  - psql -c "CREATE DATABASE travis;" -U postgres
  - psql -c "CREATE USER Book-a-Meal WITH PASSWORD 'esther96';" -U postgres

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
